---
# Configures the display manager on the installed system
# ArchTitan uses SDDM with Hyprland (Wayland session)

displaymanagers:
  - sddm

basicSetup: false

defaultDesktopEnvironment:
    executable: "Hyprland"
    desktopFile: "hyprland"
