---
# GRUB bootloader configuration for the installed system

efiBootloaderId: "ArchTitan"
installEFIFallback: true

# GRUB timeout (seconds before autobooting default entry)
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"

# Entries to add to the boot menu
defaultEntry: 0
timeout: 5
