---
# Systemd services to enable/disable on the installed system

enable:
    - sddm.service
    - titan_hw_manager.service
    - NetworkManager.service
    - systemd-timesyncd.service
    - bluetooth.service

disable:
    - choose-mirror.service
    - pacman-init.service
    - archtitan-liveuser.service
