---
unpack:
    -   source: "/run/archiso/bootmnt/arch/x86_64/airootfs.sfs"
        sourcefs: "squashfs"
        destination: ""
        exclude:
            - "etc/calamares"
            - "etc/mkinitcpio.conf.d"
            - "etc/mkinitcpio.d/linux.preset"
            - "etc/systemd/system/etc-pacman.d-gnupg.mount"
            - "etc/systemd/system/getty@tty1.service.d/autologin.conf"
            - "etc/udev/rules.d/81-dhcpcd.rules"
            - "etc/skel/.config/gnupg"
            - "etc/systemd/system/choose-mirror.service"
            - "etc/systemd/system/pacman-init.service"
            - "etc/systemd/system/archtitan-liveuser.service"
            - "root"
