---
defaultGroups:
    - wheel
    - video
    - audio
    - input
    - power
    - network
    - storage
    - optical
    - lp
    - scanner
    - kvm
    - sys
    - rfkill
autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    wheel
setRootPassword: false
doReusePassword: true
passwordRequirements:
    minLength: 4
