[Service]
ExecStart=
ExecStartPre=-/bin/sh -c 'setterm --blank 0 --powersave off --powerdown 0 > /dev/tty1 2>/dev/null || true'
ExecStart=-/usr/bin/agetty --noreset --noclear --autologin root --timeout 0 - ${TERM}
