# ArchTitan Custom Starship Prompt

format = """
[](#7DCFFF)\
$os\
$cmd_duration\
[](#7DCFFF) \
[](#7DCFFF)\
$directory\
[](#7DCFFF)
$character"""

[os]
disabled = false
style = "bg:#7DCFFF fg:#1A1B26 bold"
format = "[  ]($style)"

[cmd_duration]
min_time = 0
style = "bg:#7DCFFF fg:#1A1B26 bold"
format = "[$duration]($style)"

[directory]
style = "bg:#7DCFFF fg:#1A1B26 bold"
format = "[ $path  ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[•](#7DCFFF) [▶](#7DCFFF)"
error_symbol = "[•](#F7768E) [▶](#F7768E)"
