---
modules-search: [ local, /usr/lib/calamares/modules ]

branding: archtitan

prompt-install: false
dont-chroot: false
oem-setup: false

sequence:
- show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
- exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - initcpiocfg
    - shellprocess
    - initcpio
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - services-systemd
    - plymouthcfg
    - grubcfg
    - bootloader
    - umount
- show:
    - finished
